# Generated by Django 3.0.2 on 2020-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_required',
            field=models.CharField(max_length=15),
        ),
    ]
